
import React, { useState, FC } from 'react';
import { useAppContext } from '../context/AppContext';
import { WorkOrder, TripSettings, FinancialGoals, TripGoalSetting, SuggestedTrip } from '../types';
import { generateOptimalRoute } from '../services/geminiService';
import { AddressAutocomplete } from './AddressAutocomplete';

const inputClasses = "w-full p-2 border border-gray-300 rounded bg-white text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-500";
const labelClasses = "block text-sm font-medium text-gray-700 mb-1";

const formatMinutesToHoursAndMinutes = (totalMinutes: number): string => {
    if (isNaN(totalMinutes) || totalMinutes < 0) return 'N/A';
    const hours = Math.floor(totalMinutes / 60);
    const minutes = totalMinutes % 60;
    let result = '';
    if (hours > 0) result += `${hours} hour${hours > 1 ? 's' : ''} `;
    if (minutes > 0) result += `${minutes} minute${minutes > 1 ? 's' : ''}`;
    return result.trim() || '0 minutes';
};

interface GenerateRoutesModalProps {
    onClose: () => void;
    ordersToPlan: WorkOrder[];
    setIsLoading: (loading: boolean) => void;
    setSuggestedTrips: (trips: SuggestedTrip[]) => void;
    setAiExplanation: (explanation: string | null) => void;
    setError: (error: string | null) => void;
}

export const GenerateRoutesModal: FC<GenerateRoutesModalProps> = ({ onClose, ordersToPlan, setIsLoading, setSuggestedTrips, setAiExplanation, setError }) => {
    const { state, dispatch } = useAppContext();
    const [startLocation, setStartLocation] = useState(state.officeLocations[0]?.address || '');
    const [endLocation, setEndLocation] = useState(state.officeLocations[0]?.address || '');
    const [tripQuantity, setTripQuantity] = useState<string>('');
    const [isGenerating, setIsGenerating] = useState(false);
    const [showCancelConfirm, setShowCancelConfirm] = useState(false);

    const [overrideSettings, setOverrideSettings] = useState(false);
    const [tempTripSettings, setTempTripSettings] = useState<TripSettings>(state.tripSettings);
    
    const [violationWarning, setViolationWarning] = useState<{
        warnings: string[];
        suggestions: SuggestedTrip[];
    } | null>(null);

    const handleGenerate = async () => {
        if (!startLocation.trim() || !endLocation.trim()) {
            if (!confirm("Start or end location is blank. This might result in skewed metrics. Continue?")) {
                return;
            }
        }

        setIsGenerating(true);
        setIsLoading(true);
        setError(null);
        setSuggestedTrips([]);
        setAiExplanation(null);
        
        try {
            const numTripQuantity = tripQuantity ? parseInt(tripQuantity, 10) : undefined;
            const results = await generateOptimalRoute({
                orders: ordersToPlan,
                workOrderTypes: state.workOrderTypes,
                startLocation,
                endLocation,
                settings: overrideSettings ? tempTripSettings : state.tripSettings,
                goals: state.financialGoals,
                maxTrips: numTripQuantity,
            });

            const warnings = results.suggestions.map(s => s.violation_warning).filter((w): w is string => !!w);
            if (warnings.length > 0) {
                setViolationWarning({ warnings, suggestions: results.suggestions });
            } else {
                setSuggestedTrips(results.suggestions);
                if (results.explanation) {
                    setAiExplanation(results.explanation);
                }
                onClose();
            }
        } catch (err) {
            setError(err instanceof Error ? err.message : "An unknown error occurred");
            onClose();
        } finally {
            setIsLoading(false);
            setIsGenerating(false);
        }
    };
    
    const handleConfirmViolations = () => {
        if (violationWarning) {
            setSuggestedTrips(violationWarning.suggestions);
            if (violationWarning.suggestions.length > 1) {
                setAiExplanation("Routes were generated by overriding hard limits as requested.");
            }
            setViolationWarning(null);
            onClose();
        }
    };
    
    const handleCancelClick = () => {
        if (isGenerating) {
            setShowCancelConfirm(true);
        } else {
            onClose();
        }
    };

    const formatWarningMessage = (warning: string): string => {
        return warning.replace(/(\d+)\s+minutes/g, (_match, p1) => {
            const numMinutes = parseInt(p1, 10);
            return formatMinutesToHoursAndMinutes(numMinutes);
        });
    };

    return (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
            <div className="bg-white rounded-lg shadow-xl p-6 w-full max-w-2xl max-h-[90vh] flex flex-col relative">
                {violationWarning && (
                    <div className="absolute inset-0 bg-black bg-opacity-60 flex items-center justify-center z-[51] rounded-lg">
                        <div className="bg-white rounded-lg shadow-xl p-6 w-full max-w-lg m-4">
                            <h3 className="text-xl font-semibold text-yellow-700 mb-4">Constraint Violation Warning</h3>
                            <p className="mb-4 text-gray-700">The AI could not generate the requested number of trips without violating the following hard limits:</p>
                            <ul className="list-disc list-inside space-y-2 mb-6 text-red-600 font-medium bg-red-50 p-3 rounded-md">
                                {violationWarning.warnings.map((w, i) => <li key={i}>{formatWarningMessage(w)}</li>)}
                            </ul>
                            <p className="mb-6 text-gray-700">Do you want to approve these routes anyway?</p>
                            <div className="flex justify-end space-x-3">
                                <button onClick={() => setViolationWarning(null)} className="bg-gray-200 px-4 py-2 rounded-lg hover:bg-gray-300">Cancel</button>
                                <button onClick={handleConfirmViolations} className="bg-yellow-500 text-white px-4 py-2 rounded-lg hover:bg-yellow-600">Approve Anyway</button>
                            </div>
                        </div>
                    </div>
                )}
                 {showCancelConfirm && (
                    <div className="absolute inset-0 bg-black bg-opacity-60 flex items-center justify-center z-[51] rounded-lg">
                        <div className="bg-white rounded-lg shadow-xl p-6 w-full max-w-sm m-4">
                            <h3 className="text-lg font-bold mb-4">Cancel Generation?</h3>
                            <p className="text-gray-700 mb-6">Are you sure you want to cancel? The AI will stop planning these routes.</p>
                            <div className="flex justify-end space-x-3">
                                <button onClick={() => setShowCancelConfirm(false)} className="bg-gray-200 px-4 py-2 rounded-lg hover:bg-gray-300">Continue Generating</button>
                                <button onClick={onClose} className="bg-red-600 text-white px-4 py-2 rounded-lg hover:bg-red-700">Yes, Cancel</button>
                            </div>
                        </div>
                    </div>
                )}
                <h3 className="text-xl font-semibold mb-4 flex-shrink-0 border-b pb-3">Generate Optimal Route(s)</h3>
                <div className="flex-grow overflow-y-auto pt-4 pr-2 space-y-4">
                    <p className="text-sm text-gray-600">Configure the parameters for the AI to generate the best routes for <span className="font-bold">{ordersToPlan.length}</span> work orders.</p>
                    
                     <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                            <label htmlFor="startLocation" className={labelClasses}>Start Location</label>
                            {/* FIX: Added onCommit prop to satisfy AddressAutocompleteProps type requirement. */}
<AddressAutocomplete id="startLocation" value={startLocation} onChange={setStartLocation} onCommit={setStartLocation} placeholder="Enter address or select office" className={inputClasses}/>
                        </div>
                        <div>
                            <label htmlFor="endLocation" className={labelClasses}>End Location</label>
                            {/* FIX: Added onCommit prop to satisfy AddressAutocompleteProps type requirement. */}
<AddressAutocomplete id="endLocation" value={endLocation} onChange={setEndLocation} onCommit={setEndLocation} placeholder="Enter address or select office" className={inputClasses}/>
                        </div>
                    </div>

                    <div>
                        <label htmlFor="tripQuantity" className={labelClasses}>Trip Quantity Limit (Optional)</label>
                        <input 
                            id="tripQuantity" 
                            type="number" 
                            min="1" 
                            value={tripQuantity} 
                            onChange={e => setTripQuantity(e.target.value)} 
                            placeholder="No limit"
                            className={inputClasses}
                        />
                    </div>

                    <div>
                        <label className="flex items-center"><input type="checkbox" checked={overrideSettings} onChange={() => setOverrideSettings(!overrideSettings)} className="h-4 w-4 mr-2 rounded" /> Temporarily override default trip settings?</label>
                    </div>

                    {overrideSettings && (
                        <div className="p-4 border rounded-lg bg-gray-50 space-y-4 animate-fade-in">
                            <h4 className="font-semibold">Temporary Overrides</h4>
                            <div className="grid grid-cols-2 gap-4">
                                <div><label className={labelClasses}>Max Trip Time (hrs)</label><input type="number" value={tempTripSettings.maxTripTimeSeconds/3600} onChange={e => setTempTripSettings(p=>({...p, maxTripTimeSeconds: Number(e.target.value)*3600}))} className={inputClasses} /></div>
                                <div><label className={labelClasses}>Max Trip Mileage</label><input type="number" value={tempTripSettings.maxTripMileage} onChange={e => setTempTripSettings(p=>({...p, maxTripMileage: Number(e.target.value)}))} className={inputClasses} /></div>
                            </div>
                        </div>
                    )}
                </div>
                <div className="flex justify-end space-x-2 pt-6 mt-4 border-t flex-shrink-0">
                    <button type="button" onClick={handleCancelClick} className="bg-gray-200 px-4 py-2 rounded-lg hover:bg-gray-300">Cancel</button>
                    <button onClick={handleGenerate} disabled={isGenerating} className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 flex items-center justify-center w-36 disabled:bg-gray-400">
                        {isGenerating ? (
                            <>
                                <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                                </svg>
                                Generating...
                            </>
                        ) : 'Generate Routes'}
                    </button>
                </div>
            </div>
        </div>
    );
};
