
import React, { useState, useEffect } from 'react';
import { useAppContext } from '../context/AppContext';
import { WorkOrder, OrderStatus, WorkOrderType } from '../types';
import { AddressAutocomplete } from './AddressAutocomplete';

interface ManualOrderModalProps {
    onClose: () => void;
}

const inputClasses = "w-full p-2 border border-gray-300 rounded bg-white text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-500";
const labelClasses = "block text-sm font-medium text-gray-700";

const ManualOrderModal: React.FC<ManualOrderModalProps> = ({ onClose }) => {
    const { state, addWorkOrder } = useAppContext();
    const [formData, setFormData] = useState<Partial<WorkOrder>>({
        status: OrderStatus.PendingReview,
        dueDate: new Date().toISOString().split('T')[0],
        miscFee: 0,
    });
    const [selectedTypeId, setSelectedTypeId] = useState<string>('');
    const availableTypes = state.workOrderTypes.filter(t => !t.isArchived);

    useEffect(() => {
        if (selectedTypeId) {
            const type = state.workOrderTypes.find(t => t.id === selectedTypeId);
            const company = state.companies.find(c => c.id === type?.defaultCompanyId);
            if (type && company) {
                setFormData(prev => ({
                    ...prev,
                    typeName: type.typeName,
                    companyName: company.name,
                    baseRate: type.defaultBaseRate,
                    resources: [...type.defaultResourcesNeeded],
                }));
            }
        }
    }, [selectedTypeId, state.workOrderTypes, state.companies]);

    const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
        const { name, value } = e.target;
        setFormData(prev => ({ ...prev, [name]: value }));
    };
    
    const handleAddressChange = (address: string) => {
        setFormData(prev => ({ ...prev, address }));
    }

    const handleTypeChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
        setSelectedTypeId(e.target.value);
    }
    
    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        
        if (!selectedTypeId || !formData.address || !formData.clientName) {
            alert('Please select a work order type, and enter a client name and address.');
            return;
        }

        const newWorkOrder: WorkOrder = {
            id: '', // Will be generated by data service
            orderId: formData.orderId || `NEW-${Date.now().toString().slice(-4)}`,
            dueDate: formData.dueDate!,
            typeName: formData.typeName!,
            companyName: formData.companyName!,
            clientName: formData.clientName,
            baseRate: Number(formData.baseRate) || 0,
            miscFee: Number(formData.miscFee) || 0,
            resources: Array.isArray(formData.resources) ? formData.resources : (formData.resources as unknown as string || '').split(',').map(s => s.trim()),
            status: OrderStatus.PendingReview,
            address: formData.address,
            description: formData.description || '',
            isFollowUp: false,
        };

        const isDuplicateId = state.workOrders.some(wo => wo.orderId === newWorkOrder.orderId && wo.status !== OrderStatus.Paid);
        const isDuplicateAddress = state.workOrders.some(wo => wo.address.toLowerCase() === newWorkOrder.address.toLowerCase() && wo.status !== OrderStatus.Paid);
        if (isDuplicateId || isDuplicateAddress) {
            newWorkOrder.isFollowUp = true;
        }
        
        addWorkOrder(newWorkOrder);
        onClose();
    };

    return (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
            <div className="bg-white rounded-lg shadow-xl p-6 w-full max-w-lg max-h-full overflow-y-auto">
                <h3 className="text-xl font-semibold mb-4">New Manual Work Order</h3>
                <form onSubmit={handleSubmit} className="space-y-4">
                    <div>
                        <label htmlFor="type" className={labelClasses}>Work Order Type*</label>
                        <select id="type" value={selectedTypeId} onChange={handleTypeChange} className={inputClasses} required>
                            <option value="" disabled>Select a type...</option>
                            {availableTypes.map(t => (
                                <option key={t.id} value={t.id}>{t.typeName}</option>
                            ))}
                        </select>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                         <div>
                            <label htmlFor="orderId" className={labelClasses}>Order ID</label>
                            <input id="orderId" name="orderId" value={formData.orderId || ''} onChange={handleChange} placeholder="Optional" className={inputClasses} />
                        </div>
                        <div>
                            <label htmlFor="dueDate" className={labelClasses}>Due Date</label>
                            <input id="dueDate" name="dueDate" type="date" value={formData.dueDate || ''} onChange={handleChange} className={inputClasses} />
                        </div>
                    </div>

                     <div>
                        <label htmlFor="clientName" className={labelClasses}>Client Name*</label>
                        <input id="clientName" name="clientName" value={formData.clientName || ''} onChange={handleChange} placeholder="John Doe" className={inputClasses} required />
                    </div>
                   
                    <div>
                        <label htmlFor="address" className={labelClasses}>Address*</label>
                        {/* FIX: Added onCommit prop to satisfy AddressAutocompleteProps type requirement. */}
<AddressAutocomplete 
                            id="address" 
                            value={formData.address || ''} 
                            onChange={handleAddressChange} 
                            onCommit={handleAddressChange}
                            placeholder="123 Main St, Anytown" 
                            className={inputClasses} 
                        />
                    </div>

                    <div>
                        <label htmlFor="description" className={labelClasses}>Description / Notes</label>
                        <textarea id="description" name="description" value={formData.description || ''} onChange={handleChange} rows={3} className={inputClasses}></textarea>
                    </div>

                     <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                            <label htmlFor="baseRate" className={labelClasses}>Base Rate ($)</label>
                            <input id="baseRate" name="baseRate" type="number" value={formData.baseRate || ''} onChange={handleChange} className={inputClasses} />
                        </div>
                         <div>
                            <label htmlFor="miscFee" className={labelClasses}>Misc. Fee ($)</label>
                            <input id="miscFee" name="miscFee" type="number" value={formData.miscFee || ''} onChange={handleChange} className={inputClasses} />
                        </div>
                    </div>

                    <div>
                        <label htmlFor="resources" className={labelClasses}>Resources</label>
                        <input id="resources" name="resources" value={Array.isArray(formData.resources) ? formData.resources.join(', ') : ''} onChange={handleChange} placeholder="e.g., Notary Stamp, Scanner" className={inputClasses} />
                    </div>

                    <div className="flex justify-end space-x-2 pt-4">
                        <button type="button" onClick={onClose} className="bg-gray-200 px-4 py-2 rounded-lg hover:bg-gray-300">Cancel</button>
                        <button type="submit" className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700">Save Work Order</button>
                    </div>
                </form>
            </div>
        </div>
    );
};

export default ManualOrderModal;
